WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT    = _{ "//" ~ (!"\n" ~ ANY)* }

ident      = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
int        = @{ "-"? ~ ASCII_DIGIT+ }
float      = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }
string     = @{ "\"" ~ ( "\\\"" | (!"\"" ~ ANY) )* ~ "\"" }
boolean    = { "true" | "false" }
null       = { "null" }
undefined  = { "undefined" }

literal    = _{ float | int | string | boolean | null | undefined }

params     = { "(" ~ (ident ~ ("," ~ ident)*)? ~ ")" }
arglist    = { "(" ~ (expr ~ ("," ~ expr)*)? ~ ")" }
prop       = { ident ~ ":" ~ expr }

array      = { "[" ~ (expr ~ ("," ~ expr)* ~ (",")?)? ~ "]" }
object     = { "{" ~ (prop ~ ("," ~ prop)* ~ (",")?)? ~ "}" }

primary    = _{ literal | ident | array | object | "(" ~ expr ~ ")" }
fun        = { params ~ "=>" ~ expr }
call       = { primary ~ arglist+ }

let_       = { "let" ~ ident ~ "=" ~ expr ~ ";" ~ expr }

index      = { primary ~ "[" ~ expr ~ "]" }
access     = { primary ~ "." ~ ident }
binop      = { primary ~ ("+" | "-" | "*" | "/" | "==" | "!=" | ">" | "<" | ">=" | "<=") ~ primary }

expr       = _{ let_ | fun | call | primary | index | access | binop }
